name: segundo_proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dialog_flowtter: ^0.3.3
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dialog_flow_auth.json
  #   - images/a_dot_ham.jpeg
